### ISSUE TITLE
Game freaks out whenever I start it

### ISSUE THREAD

**Issue by BlueNerveTM** [lmk02/BlockParty#39] opened 2020-12-03 15:07 UTC
Hello, I have a problem with the plugin, I have set it up accordingly and when I try to start a game, everything works well until the game actually starts. then, this happens:

![image](https://user-images.githubusercontent.com/75436046/101044736-fc99f900-357f-11eb-8b39-0d86fc39af0f.png)

the floor rapidly shifts between every pattern added, boosts are being summoned everywhere, and the timer doesnt count down and the players do not receive color blocks. What could be the cause of the issue?

this is everything that the console displays:
[14:43:50 WARN]: java.lang.NullPointerException
[14:43:50 WARN]: java.lang.NullPointerException
[14:43:50 WARN]: java.lang.NullPointerException
[14:43:50 WARN]: java.lang.NullPointerException
[14:43:50 WARN]: java.lang.NullPointerException
[14:43:50 WARN]: java.lang.NullPointerException

 - Server version: 1.16.4 Paper
 - BlockParty version: 2.0.3.4 RELEASE
 - Additional Plugins: BuildBattle, EssentialsX, EssentialsChat, EssentialsProtect, EssentialsSpawn, HolographicDisplays, HubThat, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, NoteBlockAPI, TNTRun_reloaded, Vault, ViaBackwards, ViaVersion, VoidGenerator, WorldEdit, WorldGuard

If you need any more information, please let me know! in the meanwhile, I am eagerly waiting for your response.

**Comment by BlueNerveTM** [comment] 2020-12-03 15:13
t net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-293]
at java.lang.Thread.run(Thread.java:834) [?:?]
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-293]
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: [BlockParty] Task #49190 for BlockParty v2.0.3.4-RELEASE generated an exception
at de.pauhull.utils.message.NMSClasses.sendActionBarNMS(NMSClasses.java:123) ~[?:?]
java.lang.NullPointerException: null
at de.leonkoth.blockparty.util.Util.showActionBar(Util.java:30) ~[?:?]
at de.pauhull.utils.message.type.ActionBarMessage.send(ActionBarMessage.java:34) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-293]
at de.leonkoth.blockparty.phase.GamePhase.run(GamePhase.java:124) ~[?:?]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-293]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-293]
[15:11:48 WARN]: java.lang.NullPointerException
at java.lang.Thread.run(Thread.java:834) [?:?]
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
java.lang.NullPointerException: null
[15:11:48 WARN]: [BlockParty] Task #49190 for BlockParty v2.0.3.4-RELEASE generated an exception
at de.pauhull.utils.message.type.ActionBarMessage.send(ActionBarMessage.java:34) ~[?:?]
at de.pauhull.utils.message.NMSClasses.sendActionBarNMS(NMSClasses.java:123) ~[?:?]
at de.leonkoth.blockparty.util.Util.showActionBar(Util.java:30) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-293]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-293]
at de.leonkoth.blockparty.phase.GamePhase.run(GamePhase.java:124) ~[?:?]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-293]
at java.lang.Thread.run(Thread.java:834) [?:?]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-293]
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
java.lang.NullPointerException: null
[15:11:48 WARN]: [BlockParty] Task #49190 for BlockParty v2.0.3.4-RELEASE generated an exception
at de.pauhull.utils.message.type.ActionBarMessage.send(ActionBarMessage.java:34) ~[?:?]
at de.pauhull.utils.message.NMSClasses.sendActionBarNMS(NMSClasses.java:123) ~[?:?]
at de.leonkoth.blockparty.phase.GamePhase.run(GamePhase.java:124) ~[?:?]
at de.leonkoth.blockparty.util.Util.showActionBar(Util.java:30) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-293]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-293]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-293]
[15:11:48 WARN]: java.lang.NullPointerException
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-293]
at java.lang.Thread.run(Thread.java:834) [?:?]
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException
[15:11:48 WARN]: java.lang.NullPointerException

this is the whole output that the console displays.

**Comment by syldium** [comment] 2020-12-03 15:14
Hello,

The latest version is not compatible with version 1.16. I have adapted the plugin for this version, but it's not directly available. You can compile it yourself or download it from my [fork](https://github.com/syldium/BlockParty/releases/tag/v2.0.4-ALPHA).

**Comment by BlueNerveTM** [comment] 2020-12-03 15:17
Thank you very much for the fast response! I will install it now.

**Comment by phm07** [comment] 2021-07-10 17:41
Duplicate of #47

**Closed by phm07** 2021-07-10 17:41 UTC
